#apiVersion: apps/v1
#kind: Deployment
#metadata:
#  name: hazelcast
#spec:
#  replicas: 1
#  selector:
#    matchLabels:
#      app: hazelcast
#  template:
#    metadata:
#      labels:
#        app: hazelcast
#    spec:
#      containers:
#        - name: hazelcast
#          image: hazelcast/hazelcast:latest
#          ports:
#            - containerPort: 5701
#          env:
#            - name: HAZELCAST_KUBERNETES_ENABLED
#              value: "true"
#            - name: JAVA_OPTS
#              value: "-Dhazelcast.config=/opt/hazelcast/hazelcast.yaml"

---

apiVersion: v1
kind: Service
metadata:
  name: hazelcast-service
spec:
  selector:
    app: cachemanager-service
#    app: hazelcast
  ports:
    - name: hazelcast
      port: 5701
  type: LoadBalancer

---

#apiVersion: apps/v1
#kind: Deployment
#metadata:
#  name: hazelcast
#spec:
#  replicas: 1
#  selector:
#    matchLabels:
#      app: hazelcast
#  template:
#    metadata:
#      labels:
#        app: hazelcast
#    spec:
#      containers:
#        - name: hazelcast
#          image: hazelcast/hazelcast:latest
#          ports:
#            - containerPort: 5701
##          volumeMounts:
##            - name: hazelcast-config
##              mountPath: /opt/hazelcast
##      volumes:
##        - name: hazelcast-config
##          configMap:
##            name: hazelcast-config-map
#---
#apiVersion: v1
#kind: ConfigMap
#metadata:
#  name: hazelcast-config-map
#data:
#  hazelcast.yaml: |
#    hazelcast:
#      network:
#        join:
#          multicast:
#            enabled: false
#          kubernetes:
#            enabled: true
#            namespace: default
#            service-name: hazelcast-service
#      map:
#        sampleCache:
#          backup-count: 1
#          time-to-live-seconds: 3600
#
#---
#
#apiVersion: v1
#kind: Service
#metadata:
#  name: hazelcast-service
#spec:
#  ports:
#    - port: 5701
#  selector:
#    app: hazelcast

#---
#apiVersion: v1
#kind: ConfigMap
#metadata:
#  name: hazelcast-config
#data:
#  hazelcast.xml: |
#    <hazelcast xmlns="http://www.hazelcast.com/schema/config"
#               xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
#               xsi:schemaLocation="http://www.hazelcast.com/schema/config
#                http://www.hazelcast.com/schema/config/hazelcast-config-4.0.xsd">
#        <network>
#            <join>
#                <multicast enabled="false"/>
#                <tcp-ip enabled="true">
#                    <member>localhost</member>
#                </tcp-ip>
#            </join>
#        </network>
#    </hazelcast>
