#apiVersion: apps/v1
#kind: Deployment
#metadata:
#  name: cachemanager
#spec:
#  replicas: 1
#  selector:
#    matchLabels:
#      app: cachemanager
#  template:
#    metadata:
#      labels:
#        app: cachemanager
#    spec:
#      containers:
#        - name: app
#          image: poornachandravc/cachemanager:1.0.0
#          ports:
#            - containerPort: 8080
#          imagePullPolicy: Always

---

#apiVersion: apps/v1
#kind: Deployment
#metadata:
#  name: cachemanager
#spec:
#  replicas: 3
#  selector:
#    matchLabels:
#      app: cachemanager
#  template:
#    metadata:
#      labels:
#        app: cachemanager
#    spec:
#      containers:
#        - name: cachemanager
#          image: poornachandravc/cachemanager:1.0.0
#          ports:
#            - containerPort: 8080
#          imagePullPolicy: Always
#          env:
#            - name: HAZELCAST_HOST
#              value: "localhost"
#          volumeMounts:
#            - mountPath: /config
#              name: hazelcast-config
#              subPath: hazelcast.xml
#        - name: hazelcast
#          image: hazelcast/hazelcast:latest
#          ports:
#            - containerPort: 5701
#          volumeMounts:
#            - mountPath: /config
#              name: hazelcast-config
#              subPath: hazelcast.xml
#      volumes:
#        - name: hazelcast-config
#          configMap:
#            name: hazelcast-config

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: cachemanager
  labels:
    app: cachemanager
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cachemanager
  template:
    metadata:
      labels:
        app: cachemanager
    spec:
      containers:
        - name: cachemanager
          image: poornachandravc/cachemanager:1.0.0
          ports:
            - name: http
              containerPort: 8080
            - name: multicast
              containerPort: 5701
---
apiVersion: v1
kind: Service
metadata:
  name: cachemanager
  labels:
    app: cachemanager
spec:
  ports:
    - port: 8080
      protocol: TCP
  selector:
    app: cachemanager
  type: NodePort