apiVersion: v1
kind: PersistentVolume
metadata:
  name: cachemanager-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/cachemanager

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cachemanager-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: cachemanager
  labels:
    app: cachemanager
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cachemanager
  template:
    metadata:
      labels:
        app: cachemanager
    spec:
      containers:
        - name: cachemanager
          image: poornachandravc/cachemanager:1.0.0
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
            - name: multicast
              containerPort: 5701
          volumeMounts:
            - mountPath: /data
              name: cachemanager-storage
      volumes:
        - name: cachemanager-storage
          persistentVolumeClaim:
            claimName: cachemanager-pvc

---