apiVersion: v1
kind: Service
metadata:
  name: postgresql-service
spec:
  ports:
    - port: 5432  # PostgreSQL default port
  selector:
    app: postgresql  # Label selector for your PostgreSQL pod

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
  labels:
    app: postgresql
spec:
  replicas: 1  # Typically 1 for PostgreSQL in a standalone configuration
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
        - name: postgresql
          image: postgres:latest
          ports:
            - containerPort: 5432  # PostgreSQL default port
          env:
            - name: POSTGRES_DB
              value: sampledb  # Create the database with this name
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgrespassword
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgresql-storage
      volumes:
        - name: postgresql-storage
          persistentVolumeClaim:
            claimName: postgresql-pvc  # Ensure this matches the PersistentVolumeClaim name for PostgreSQL

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-pvc
spec:
  accessModes:
    - ReadWriteOnce  # Adjust based on your storage requirements
  resources:
    requests:
      storage: 1Gi  # Adjust the storage size as per your requirements


---