#apiVersion: v1
#kind: Service
#metadata:
#  name: cachemanager
#spec:
#  selector:
#    app: cachemanager
#  ports:
#    - port: 80
#      targetPort: 8080
#  type: LoadBalancer

---

apiVersion: v1
kind: Service
metadata:
  name: hazelcast-service
spec:
  selector:
    app: cachemanager
  ports:
    - name: hazelcast
      port: 5701
  type: LoadBalancer